export const LC_OVERVIEW_DATA_KEY = 'MCA-OVERVIEW-DATA';
export const LC_OVERVIEW_EXP_DATE_KEY = 'MCA-OVERVIEW-EXP-DATE';

export const LC_DETAILS_DATA_KEY = 'MCA-DETAILS-DATA';
export const LS_DETAILS_EXP_DATE_KEY = 'MCA-DETAILS-EXP-DATE';
